print("ผลการแข่งขันระหว่าง ManU-Liverpool")
manU = input("ประตูที่ ManU ทำได้: >> ")
liver = input("ประตูที่ Liverpool ทำได้: >> ")
print()
print("ผลการแข่งขันระหว่าง Arsenal-Chelsea")
arsenal = input("ประตูที่ Arsenal ทำได้: >> ")
chelsea = input("ประตูที่ Chelsea ทำได้: >> ")
print()
print("ผลการแข่งขันระหว่าง Spur-ManCity")
spur = input("ประตูที่ Spur ทำได้: >> ")
manCity = input("ประตูที่ ManCity ทำได้: >> ")
print()
print("สรุปผลการแข่งขัน")
print("ManUnited ("+manU+" - "+liver+") Liverpool")
print("Arsenal ("+arsenal+" - "+chelsea+") Chelsea")
print("Spur ("+spur+" - "+manCity+") ManCity")